import type { Metadata } from "next";
import { NextUIProvider } from "@nextui-org/react";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/common/navbar"; // Update the import path

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider>
          <Navbar />
          <main className="flex min-h-screen flex-col items-center justify-between px-4 sm:px-8 md:px-16 lg:px-24">
            {children}
          </main>
        </NextUIProvider>
      </body>
    </html>
  );
}
